version: '2'

services:
  _common:
    environment:
      POSTGRES_PASSWORD:
      PROBEDOCK_DATABASE_NAME: probedock
      PROBEDOCK_DATABASE_USERNAME: probedock
      PROBEDOCK_DATABASE_PASSWORD:


  bakdb:
    image: postgres:9.5.2
    extends:
      service: _common
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/backups/postgresql:/backups
    networks:
      - probenet
    entrypoint: sh -c 'exec pg_dump -h ${PROBEDOCK_ENV}_db -p 5432 -U postgres probedock' | gzip > /backups/postgres/${PROBEDOCK_ENV}_${PROBEDOCK_DATE}_db.sql.gz || exit 1

  db:
    image: postgres:9.5.2
    extends:
      service: _common
    container_name: db
    volumes:
      - ./pipeline/docker/scripts/postgres-init.sh:/docker-entrypoint-initdb.d
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/postgresql/data:/var/lib/postgresql/data
    networks:
      - probenet

  cache:
    image: redis:3.2.0
    container_name: cache
    command: redis-server --appendonly yes
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/redis/data:/data
    networks:
      - probenet

  task:
    image: probedock/probedock
    extends:
      service: _common
    networks:
      - probenet

  waitdb:
    image: probedock/jenkins
    networks:
      - probenet
    entrypoint: ./wait-for-it.sh db:5432

  waitcache:
    image: probedock/jenkins
    networks:
      - probenet
    entrypoint: ./wait-for-it.sh cache:6379

networks:
  probenet: