version: '2'

services:
  _common:
    image: jenkinsci/jenkins:2.3
    environment:
      RAILS_ENV: production
      POSTGRES_PASSWORD:
      PROBEDOCK_DATABASE_HOST: ${PROBEDOCK_ENV}_db
      PROBEDOCK_DATABASE_NAME: probedock
      PROBEDOCK_DATABASE_USERNAME: probedock
      PROBEDOCK_DATABASE_PASSWORD:
      PROBEDOCK_REDIS_URL: "${PROBEDOCK_ENV}_cache:6379:0"
      PROBEDOCK_SECRET_KEY_BASE:
      PROBEDOCK_JWT_SECRET:
      PROBEDOCK_LOG_LEVEL:
      PROBEDOCK_LOG_TO_STDOUT: "1"
      PROBEDOCK_MAIL_ADDRESS:
      PROBEDOCK_MAIL_PORT:
      PROBEDOCK_MAIL_DOMAIN:
      PROBEDOCK_MAIL_USERNAME:
      PROBEDOCK_MAIL_PASSWORD:
      PROBEDOCK_MAIL_AUTHENTICATION:
      PROBEDOCK_MAIL_FROM:
      PROBEDOCK_MAIL_FROM_NAME:
      PROBEDOCK_APP_PROTOCOL:
      PROBEDOCK_APP_HOST:
      PROBEDOCK_APP_PORT:
      PROBEDOCK_UNICORN_USER: root
      PROBEDOCK_UNICORN_WORKERS:

  bakDb:
    image: probedock/postgres
    extends:
      service: _common
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/backups/postgresql:/backups
    networks:
      - probenet
    entrypoint: sh -c 'exec pg_dump -h ${PROBEDOCK_ENV}_db -p 5432 -U postgres probedock' | gzip > /backups/postgres/${PROBEDOCK_ENV}_${PROBEDOCK_DATE}_db.sql.gz || exit 1

  db:
    image: probedock/postgres
    extends:
      service: _common
    container_name: ${PROBEDOCK_ENV}_db
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/postgresql/data:/var/lib/postgresql/data
    networks:
      - probenet

  cache:
    image: redis:3.2.0
    container_name: ${PROBEDOCK_ENV}_cache
    command: redis-server --appendonly yes
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/redis/data:/data
    networks:
      - probenet

  jenkins:
    image: probedock/jenkins
    container_name: jenkins
    volumes_from:
      - jenkinsData
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080

  jenkinsData:
    image: probedock/jenkins
    container_name: jenkins_data
    entrypoint: /bin/bash
    volumes:
      - /jenkins:/var/jenkins_home

  task:
    image: probedock/probedock
    extends:
      service: _common
    networks:
      - probenet

  waitDb:
    image: probedock/jenkins
    networks:
      - probenet
    entrypoint: ./wait-for-it.sh ${PROBEDOCK_ENV}_db:5432

  waitCache:
    image: probedock/jenkins
    networks:
      - probenet
    entrypoint: ./wait-for-it.sh ${PROBEDOCK_ENV}_cache:6379

networks:
  probenet: