version: '2'

services:
  db:
    image: postgres:9.4
    volumes:
      - ./pipeline/docker/scripts/postgres-init.sh:/docker-entrypoint-initdb.d
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/postgresql/data:/var/lib/postgresql/data
    networks:
      - probenet
    environment:
      POSTGRES_PASSWORD:
      PROBEDOCK_DATABASE_NAME: probedock
      PROBEDOCK_DATABASE_USERNAME: probedock
      PROBEDOCK_DATABASE_PASSWORD:

  cache:
    image: redis:2.8
    command: redis-server --appendonly yes
    volumes:
      - ${PROBEDOCK_DATA_PATH}/${PROBEDOCK_ENV}/redis/data:/data
    networks:
      - probenet

  waitdb:
    image: aanand/wait
    networks:
      - probenet
    links:
      - db:db

  waitcache:
    image: aanand/wait
    networks:
      - probenet
    links:
      - cache:cache

networks:
  probenet: