node {
    dir('"../../workspace/${JOB_NAME}@script"') {
        stage 'Start docker'
        sh 'jenkins/scripts/docker.sh'
        stage 'Checkout Probe Dock'
        checkout poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'WipeWorkspace'], [$class: 'RelativeTargetDirectory', relativeTargetDir: 'probedock']], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:probedock/probedock.git']]]
        stage 'Create database'
        sh 'docker-compose -p ${PROBEDOCK_ENV} run db'
    }
}